from setuptools import setup

setup(
  name='pyfeed_info',
  version='1.0.1',
  packages=['test', 'venv.lib.python3.6.distutils', 'venv.lib.python3.6.encodings', 'venv.lib.python3.6.importlib',
            'venv.lib.python3.6.collections', 'venv.lib.python3.6.site-packages.pip',
            'venv.lib.python3.6.site-packages.pip.req', 'venv.lib.python3.6.site-packages.pip.vcs',
            'venv.lib.python3.6.site-packages.pip.utils', 'venv.lib.python3.6.site-packages.pip.compat',
            'venv.lib.python3.6.site-packages.pip.models', 'venv.lib.python3.6.site-packages.pip._vendor',
            'venv.lib.python3.6.site-packages.pip._vendor.distlib',
            'venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
            'venv.lib.python3.6.site-packages.pip._vendor.colorama',
            'venv.lib.python3.6.site-packages.pip._vendor.html5lib',
            'venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
            'venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
            'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
            'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
            'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
            'venv.lib.python3.6.site-packages.pip._vendor.lockfile',
            'venv.lib.python3.6.site-packages.pip._vendor.progress',
            'venv.lib.python3.6.site-packages.pip._vendor.requests',
            'venv.lib.python3.6.site-packages.pip._vendor.requests.packages',
            'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.chardet',
            'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3',
            'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.util',
            'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.contrib',
            'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.packages',
            'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
            'venv.lib.python3.6.site-packages.pip._vendor.packaging',
            'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
            'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
            'venv.lib.python3.6.site-packages.pip._vendor.webencodings',
            'venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
            'venv.lib.python3.6.site-packages.pip.commands', 'venv.lib.python3.6.site-packages.pip.operations',
            'venv.lib.python3.6.site-packages.idna', 'venv.lib.python3.6.site-packages.wheel',
            'venv.lib.python3.6.site-packages.wheel.tool', 'venv.lib.python3.6.site-packages.wheel.signatures',
            'venv.lib.python3.6.site-packages.certifi', 'venv.lib.python3.6.site-packages.chardet',
            'venv.lib.python3.6.site-packages.chardet.cli', 'venv.lib.python3.6.site-packages.urllib3',
            'venv.lib.python3.6.site-packages.urllib3.util', 'venv.lib.python3.6.site-packages.urllib3.contrib',
            'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
            'venv.lib.python3.6.site-packages.urllib3.packages',
            'venv.lib.python3.6.site-packages.urllib3.packages.backports',
            'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
            'venv.lib.python3.6.site-packages.dateutil', 'venv.lib.python3.6.site-packages.dateutil.tz',
            'venv.lib.python3.6.site-packages.dateutil.zoneinfo', 'venv.lib.python3.6.site-packages.requests',
            'venv.lib.python3.6.site-packages.setuptools', 'venv.lib.python3.6.site-packages.setuptools.extern',
            'venv.lib.python3.6.site-packages.setuptools.command', 'venv.lib.python3.6.site-packages.parameterized',
            'venv.lib.python3.6.site-packages.pkg_resources', 'venv.lib.python3.6.site-packages.pkg_resources.extern',
            'venv.lib.python3.6.site-packages.pkg_resources._vendor',
            'venv.lib.python3.6.site-packages.pkg_resources._vendor.packaging',
            'venv.lib.python3.6.site-packages.nose_parameterized'],
  url='https://github.com/ymatsukawa/pyfeed_info',
  license='MIT',
  author='ymatsukawa',
  author_email='',
  description='get rss feeds and post them to another service'
)
