# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'
require 'bundler'

namespace :root_project do
  task :prepare do
    Bundler.with_clean_env do
      exec('bundle install --path ./bundler')
    end
  end
end

namespace :slack_api do
  task :prepare do
    Bundler.with_clean_env do
      ENV['BUNDLE_GEMFILE'] = Rails.root.join('vendor', 'slack_api', 'Gemfile').to_s
      exec('bundle install --path ./bundler')
    end
  end
end

namespace :mock_server do
  task :prepare do
    Bundler.with_clean_env do
      ENV['BUNDLE_GEMFILE'] = Rails.root.join('vendor', 'mock_server', 'Gemfile').to_s
      exec('bundle install --path ./bundler')
    end
  end

  task :run do # launch in sub-shell
    Dir.chdir('./vendor/mock_server') do
      exec('ruby server.rb')
    end
  end
end

Rails.application.load_tasks
