version: '3'
services:
  web:
    image: node:12
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    command: bash -c "npm start"
  cdn:
    image: nginx:latest
    volumes:
      - ./nginx/cdn_nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/contents/:/var/www/contents
    ports:
      - 8080:80
  load_balancer:
    image: nginx:latest
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
